Feature/postgres
LekiTech/gafargan-bot pull request #3
Opened 2024-05-30 11:23 UTC by MagomedovArthur

2024-06-01 11:29 UTC, tadzjibov commented
Besides all other comments, when I tried running the project locally I got this error: `java: package io.lekitech does not exist`
How to solve it? I did run this project earlier and everything was working including the numbers
![image](https://github.com/LekiTech/gafargan-bot/assets/9715475/f9dc00f5-72f4-49a0-99b2-3b5969f880da)

2024-06-01 11:30 UTC, tadzjibov requested changes

2024-06-01 11:30 UTC, tadzjibov commented on src/main/java/core/ExportDataFromFirebase.java
Probably you meant **import** instead of **export**? So the class should be `ImportFirebaseData`

2024-06-01 11:30 UTC, tadzjibov commented on lib/javax.ejb.jar
Why did you use all these jars? Couldn't you include them using `pom.xml`?

2024-06-01 11:30 UTC, tadzjibov commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/gafargan_bot
`gafargan_bot_db` is more suitable name for database instead of `gafargan_bot`

2024-06-01 11:30 UTC, tadzjibov commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/gafargan_bot
Also, where do you set it in java code? I couldn't find it

2024-06-01 11:30 UTC, tadzjibov commented on src/main/resources/application.properties
Now you have:
- `config.properties` file to get dictionary
- `.env` file to get `TELEGRAM_API_TOKEN`
- `application.properties` to get spring configs

It is better to put everything in one place. I would suggest moving all your configs to `application.properties` because they are used anyway by spring, and because we can set them via terminal when running docker container

2024-06-01 13:14 UTC, MagomedovArthur commented on lib/javax.ejb.jar
Когда возился со спрингом видимо случайно как-то загрузил через Idea и оттуда закомитил в гитхаб, уже не помню. Попробую удалить их.

2024-06-01 13:14 UTC, MagomedovArthur commented on src/main/java/core/ExportDataFromFirebase.java
Да, путаю эти понятия всегда). Исправлю.

2024-06-01 13:14 UTC, MagomedovArthur commented on src/main/resources/application.properties
OK.  В целом по проекту много изменений можно внести после того как Spring внедрил. Много лишнего кода убрать, упроситить и т.д. я думаю

2024-06-09 12:11 UTC, tadzjibov approved these changes

2024-06-09 12:11 UTC, merged